React Native Gesture Handler: 2.5.0#commit + yoga patch -> 2.6.0 (#885)
* Add react-native-gesture-handler w yoga patch

Close: https://github.com/leotm/react-native-template-new-architecture/issues/884

* Update pod lockfile

* Bump RNGH from 2.5.0 to latest commit for Android

* Remove stale RNGH 2.5.0 yoga patch

* Bump RNGH from 9a4bef2 to 917295f (latest) for iOS (CocoaPods)

* Build only x86_64 on Android and clean after

Getting:

You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 44 MB

java.io.IOException: No space left on device

* Update RNGH to 2.6.0

Following patch #917295fbbceff36f94643edf1a15cbcb55933ec6

And update pod

* Revert "Build only x86_64 on Android and clean after"

This reverts commit e1fbd877fe9eaa9155310e85aa5b0b9ed2fca92b.