ESLint disable react/require-optimization on storybook Welcome class
Error: Component is not optimized. Please add a shouldComponentUpdate method

Refactor this old class verbose example later.

Adding default implementation shouldComponentUpdate return true seems ironic for a minimal example, especially when this lifecycle fn is intended as an override.