Fix App-test error TS2604
JSX element type 'App' does not have any construct or call signatures

Export App to favour named import in test,  since not testing storybook here