Finish Android RN 0.68.0-rc.2 upg w new arch (Fabric/TurboModules)
These steps work
- git clean -fdx && yarn
- Android Studio > Project Structure > Modules > ReactAndroid > NDK Version > 24.0.8079956 (not in docs)
- add to android/local.properties: ndk.dir=/Users/<user>/Library/Android/sdk/ndk/24.0.8079956
- yarn start, (wipe device), Make/Build/Run

But Android Studio > Clean (./gradlew clean) takes mins then fails (then building too always fails).

Debug later, looks related to react-native-screens:

---

> Task :app:packageReactNdkReleaseLibs
Execution optimizations have been disabled for task ':app:packageReactNdkReleaseLibs' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build/react-ndk/exported'. Reason: Task ':app:generateCodegenSchemaFromJavaScript' uses this output of task ':app:packageReactNdkReleaseLibs' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/src/main/jni/prebuilt/lib'. Reason: Task ':app:packageReactNdkReleaseLibs' uses this output of task ':ReactAndroid:packageReactNdkDebugLibsForBuck' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.4/userguide/validation_problems.html#implicit_dependency for more details about this problem.

> Task :react-native-screens:externalNativeBuildCleanRelease FAILED
Clean rnscreens_modules x86,react_codegen_rnscreens x86,rnscreens_common x86
C/C++: fcntl(): Bad file descriptor
C/C++: /Users/<user>/Library/Android/sdk/ndk/24.0.8079956/build/core/prebuilt-library.mk:51: *** Android NDK: Aborting    .  Stop.

—

Terminal Clean

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-screens:externalNativeBuildCleanRelease'.
> Build command failed.
  Error while executing process /Users/<user>/Library/Android/sdk/ndk/24.0.8079956/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/src/main/jni/Android.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=0 NDK_OUT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/build/intermediates/cxx/Release/6a342fj6/obj NDK_LIBS_OUT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/build/intermediates/cxx/Release/6a342fj6/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build REACT_ANDROID_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/../node_modules/react-native/ReactAndroid/build clean}
  Android NDK: ERROR:/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file
  Android NDK: Check that /Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build/react-ndk/exported/x86/libfb.so exists  or that its path is correct

  fcntl(): Bad file descriptor
  /Users/<user>/Library/Android/sdk/ndk/24.0.8079956/build/core/prebuilt-library.mk:51: *** Android NDK: Aborting    .  Stop.

* ...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 6m 25s
69 actionable tasks: 38 executed, 31 up-to-date

—

Android Studio Clean

Build command failed.
Error while executing process /Users/<user>/Library/Android/sdk/ndk/24.0.8079956/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/src/main/jni/Android.mk APP_ABI=armeabi-v7a NDK_ALL_ABIS=armeabi-v7a NDK_DEBUG=1 NDK_OUT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/2z2b85v4/obj NDK_LIBS_OUT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/build/intermediates/cxx/Debug/2z2b85v4/lib APP_CFLAGS+=-Wall APP_CFLAGS+=-Werror APP_CFLAGS+=-fexceptions APP_CFLAGS+=-frtti APP_CFLAGS+=-DWITH_INSPECTOR=1 APP_CPPFLAGS+=-std=c++17 APP_PLATFORM=android-21 APP_STL=c++_shared NDK_TOOLCHAIN_VERSION=clang GENERATED_SRC_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build/generated/source PROJECT_BUILD_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build REACT_ANDROID_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/../node_modules/react-native/ReactAndroid REACT_ANDROID_BUILD_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/android/../node_modules/react-native/ReactAndroid/build clean}
Android NDK: ERROR:/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native-screens/android/src/main/jni/Android.mk:fb: LOCAL_SRC_FILES points to a missing file
Android NDK: Check that /Users/<user>/Documents/GitHub/react-native-template-typescript/android/app/build/react-ndk/exported/armeabi-v7a/libfb.so exists  or that its path is correct

fcntl(): Bad file descriptor
/Users/<user>/Library/Android/sdk/ndk/24.0.8079956/build/core/prebuilt-library.mk:51: *** Android NDK: Aborting    .  Stop.

—

Andorid Studio Make

[CXX1405] error when building with ndkBuild using /Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk: Build command failed.
Error while executing process /Users/<user>/Library/Android/sdk/ndk/24.0.8079956/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-21 NDK_OUT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/3w2v1at3/obj NDK_LIBS_OUT=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/build/intermediates/cxx/Debug/3w2v1at3/lib NDK_APPLICATION_MK=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk THIRD_PARTY_NDK_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/build/third-party-ndk REACT_COMMON_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/../ReactCommon REACT_GENERATED_SRC_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/build/generated/source REACT_SRC_DIR=/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react -j8 --output-sync=none APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
Android NDK: /Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/../ReactCommon/butter/Android.mk: Cannot find module with tag 'glog' in import path
Android NDK: Are you sure your NDK_MODULE_PATH variable is properly defined ?
Android NDK: The following directories were searched:
Android NDK:

/Users/<user>/Documents/GitHub/react-native-template-typescript/node_modules/react-native/ReactAndroid/../ReactCommon/butter/Android.mk:28: *** Android NDK: Aborting.    .  Stop.