Upgrade React Native from 0.70.6 to 0.71.0-rc.5 (#1316)
* Upgrade React Native from 0.70.6 to 0.71.0-rc.5 on iOS
* Upgrade React Native from 0.70.6 to 0.71.0-rc.5 on Android

* Android CI now fast 🔥

* Temporarily remove 4 libs causing Android build errors
  * "react-native-gesture-handler": "2.8.0" (WIP)
  * "react-native-reanimated": "3.0.0-rc.8" (WIP + iOS)
  * "react-native-safe-area-context": "4.4.1" (raised, not started)
  * "react-native-screens": "3.18.2 (WIP)

* Update Pods

* Update Jest snapshot

* Add npx react-native info to Android CI
* Bump ubuntu-22.04 JDK from 11 to 19 (Temurin, matrix inc)

* Remove package.json>codegenConfig
* Fixes Gradle Wrapper (RN CLI runs fine) release build mergeDexRelease error
* Or libs fail (check JDK 18/19 + Gradle 7.5.1/7.6)
  * "@react-native-async-storage/async-storage": "1.17.11",
  * "@react-native-community/checkbox": "0.5.14",
  * "@react-native-community/datetimepicker": "6.3.5",
  * "@react-native-community/slider": "4.4.0",

* Multiple issues closed
* Multiple dep man PRs unblocked
* Multiple 3rd party issues spawned :suspect: 
* One or more PRs closed

---

> Could not open cp_proj generic class cache for build file '.../node_modules/@react-native-community/slider/android/build.gradle' (/Users/leo/.gradle/caches/7.5.1/scripts/93eeycp2z38sr2ij8ab48qaju).
   > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63

---

* What went wrong:
Execution failed for task ':app:mergeDexRelease'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
           Type com.facebook.react.viewmanagers.ActivityIndicatorViewManagerInterface is defined multiple times: /home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/android/app/build/intermediates/project_dex_archive/release/out/com/facebook/react/viewmanagers/ActivityIndicatorViewManagerInterface.dex, /home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/android/app/build/intermediates/external_libs_dex/release/mergeExtDexRelease/classes.dex