Update react-native monorepo (patch) to v0.71.12 (#1713)
* Update react-native monorepo

* Update pods

- RN (+hermes-engine) from 0.71.6 to 0.71.12
- react-native-safe-area-context from 4.5.2 to 4.5.5
- RNCAsyncStorage from 1.18.1 to 1.18.2
- RNCCheckbox from 0.5.15 to 0.5.16

* Bump iOS CI from macos-12 to macos-13

TypeError: str.replace is not a function
    at inlineString (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-tools/build/errors.js:25:33)

Try to avoid downgrading @react-native-community/cli from 11.2.3

└─┬ react-native@0.71.12
  └── @react-native-community/cli@10.2.4

Otherwise switch from 14.2 (default) to 15.0 (beta)	in CI

* Bump README.md RN ver from 0.71.6 to 0.71.12

---------

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>
Co-authored-by: LeoTM <1881059+leotm@users.noreply.github.com>