Bump iOS CI from macos-12 to macos-13
TypeError: str.replace is not a function
    at inlineString (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-tools/build/errors.js:25:33)

Try to avoid downgrading @react-native-community/cli from 11.2.3

└─┬ react-native@0.71.12
  └── @react-native-community/cli@10.2.4

Otherwise switch from 14.2 (default) to 15.0 (beta)	in CI